---
title: "Algorithm 3"
output: html_notebook
---


```{r}
library(caret)
library(ranger)
library(tidyverse)
library(e1071)
library(readxl)
red <- read_excel("C:/Users/sarah/Desktop/info8000/winequalityred.xlsx", 
    col_types = c("numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))
library(caret)
library(ranger)
library(tidyverse)
library(e1071)
set.seed(65468)
inTraining<-createDataPartition(red$quality,p=.75,list = FALSE)
training<-red[inTraining,]
testing<-red[-inTraining,]
fitControl<-trainControl(## 10-fold CV
  method = "cv",
  number=10,
  ##repeated ten times
  repeats = 10)

rfFit1<- train(quality ~.,data=training,
                method="rf",
                trControl = fitControl)
rfFit1
```
```{r}
rf2fit<- train(quality ~ alcohol + citricacid + volatileacidity + totalsulfurdioxide + sulphates + fixedacidity + density,
               data=training,
               method="rf",
               trControl=fitControl)
rf2fit
```
performs best when all variables are included!Still not great though...
