---
title: "Wine Quality Data Analysis"
author: "Sarah Ferrero"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wine Quality Distribution
The following code will evaluate the basic descriptive statistics of the Wine Quality variable of interest/ variable to be tested in the machine learning algorithms.

```{r}
#import and view dataset
library(readxl)
winequalityred <- read_excel("C:/Users/sarah/Desktop/info8000/winequalityred.xlsx", 
    col_types = c("numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))
QualityMax<-max(winequalityred$quality)
QualityMin<-min(winequalityred$quality)
QualityAverage<-mean(winequalityred$quality)
QualityMedian<-median(winequalityred$quality)
QualityMax
QualityMin
QualityAverage
QualityMedian
QualityMode <- names(which.max(table(winequalityred$quality)))
QualityMode
QualityStandardDeviation <- sd(winequalityred$quality)
QualityStandardDeviation
#as was stated in the UCI machine learning respository, there aren't many extreme values (very good/very bad wines). most of the wines are "Normal".

```

## Wine Quality Distribution Graph


```{r winequalityred}
ggplot(data=winequalityred, aes(x=quality)) +
    geom_histogram(binwidth=1, color='black', fill='white') +
    coord_cartesian(xlim=c(0,10)) +
    geom_vline(xintercept = QualityMedian, linetype='longdash', alpha=.5) +
    geom_vline(xintercept = QualityAverage, linetype=1, color='green', alpha=.5) +
    xlab("Wine Quality") +
    ylab("Number of Observations")
```

##Independent Variable Descripive Statistics
```{r winequalityred}
fixedac
volatileac
citric
sugar
chloride
freeso2
totalso2
density
ph
sulfates
alcohol
```
##Variable Correlations
```{r winequalityred}

```

